### ISSUE TITLE
Consider mentioning Tzlvt

### ISSUE THREAD

**Issue by ksixty** [danilkinkin/buckweat#47]
Circa 2014 a friend of mine made a web app with the same idea and principles that Buckwheat has.

That the very same idea occurred to you may be a mere coincidence, just if it's not — consider mentioning the original app and its authors: https://www.fuckgrechka.ru/tzlvt/.

I'm enjoying the app btw, cheers!

**Comment by danilkinkin** [comment]
Yes, a couple of years ago I used “Тяжеловато”, and it inspired me to create buckwheat. It would probably be right to give respect and mention it in the README.

Thank you
