### ISSUE TITLE
Add days to skip spending

### ISSUE THREAD

**Issue by Wjxfi** [danilkinkin/buckweat#64]
I have a budget of 1,000 every day (my currency). But each week on weekends and Sundays I do not make sense to spend (I want to skip a day or set a custom value for the day). For this reason, I specify 20 000 (per month), not 30 000. But the application shows that I spend 667 per day if I specify 20,000. This is a mistake (I spend a thousand). Do something so it can be corrected. There is no point in using the app right now

------------------------------

У меня есть бюджет в 1000 каждый день (моя валюта). Но каждую неделю по субботам и воскресеньям мне нет смысла тратить (я хочу пропустить день или установить пользовательское значение для дня). По этой причине я указываю 20 000 (в месяц), а не 30 000. Но приложение показывает, что я трачу 667 в день, если я указываю 20 000. Это ошибка (я трачу тысячу). Сделайте что-нибудь, чтобы это можно было исправить. Сейчас нет смысла пользоваться приложением.

**Comment by danilkinkin** [comment]
Hello, sorry for not answering for a long time.

It seems to me that this is an unnecessary functionality for rather rare cases.

And how would you like to count if you nevertheless made a waste on a missed day?
